#!/usr/bin/env python3

import sys
from antlr4 import *
from RobotLexer import RobotLexer
from RobotParser import RobotParser
from antlr4.error.ErrorListener import ErrorListener

class InstructionExtractor(ParseTreeListener):
    def __init__(self):
        self.instructions = []

    def exitPolite_move(self, ctx):
        number = ctx.NUMBER().getText()
        self.instructions.append(f"MOV,{number}")

    def exitPolite_turn(self, ctx):
        degree = ctx.DEGREE().getText()
        self.instructions.append(f"TURN,{degree}")

class CustomErrorListener(ErrorListener):
    def __init__(self):
        super().__init__()
        self.errors = []

    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e):
        self.errors.append(f"Line {line}:{column} - {msg}")

class RobotANTLRCompiler:
    def __init__(self):
        self.error_listener = CustomErrorListener()

    def compile(self, input_text):
        try:
            # Clear errors before each parse
            self.error_listener.errors = []

            input_stream = InputStream(input_text)
            lexer = RobotLexer(input_stream)
            token_stream = CommonTokenStream(lexer)
            
            parser = RobotParser(token_stream)
            parser.removeErrorListeners()
            parser.addErrorListener(self.error_listener)

            tree = parser.program()

            if self.error_listener.errors:
                return None, self.error_listener.errors

            extractor = InstructionExtractor()
            walker = ParseTreeWalker()
            walker.walk(extractor, tree)

            return extractor.instructions, []
        except Exception as e:
            return None, [f"Compilation error: {e}"]

    def compile_to_file(self, input_text, output_file):
        instructions, errors = self.compile(input_text)

        if errors:
            return False, errors

        try:
            with open(output_file, 'w') as f:
                f.write("# Generated by ANTLR Robot Compiler\n")
                for instruction in instructions:
                    f.write(f"{instruction}\n")
            return True, []
        except Exception as e:
            return False, [f"File write error: {e}"]

if __name__ == "__main__":
    compiler = RobotANTLRCompiler()

    for i, sentence in enumerate([
        "Robot please move 3 blocks ahead",
        "Could you turn 90 degrees",
        "Robot could you move 2 blocks ahead and turn 180 degrees",
        "Please move 1 blocks ahead, then turn 270 degrees"
    ], 1):
        print(f"\n=== Test {i} ===")
        print(f"Input: {sentence}")
        result, errors = compiler.compile(sentence)
        if errors:
            print("❌ Errors:", errors)
        else:
            print("✅ Compiled Instructions:")
            for line in result:
                print("  ", line)
